'use client';
import { createElement, useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Box, Layers3, Ruler, GitBranch, Component, Cpu, Menu, X, Sun, Moon, Search, Check, Code2 as Github, Download, BookOpen } from 'lucide-react';
import build from './generated-build.json';
type Words = [string,string];
type Language = 'en'|'yue'|'both';
const repo = 'https://github.com/Ding-Ding-Projects/precision-cad';
const features: {id:string; icon:typeof Box; title:Words; summary:Words; body:Words; acceptance:Words; phase:number}[] = [
{id:'modelling',icon:Box,title:['Parametric modelling','參數式建模'],summary:['Design intent, built into every feature.','將設計意圖保留喺每個特徵。'],body:['Planned dimension-driven sketches, extrudes, revolves, sweeps, lofts, booleans, fillets, shells and patterns. Upstream edits regenerate dependent features. Ambiguous face references require explicit repair instead of silently attaching to a different face.','規劃包括尺寸驅動草圖、拉伸、旋轉、掃掠、放樣、布林運算、圓角、抽殼同陣列。修改上游設定會重新計算相關特徵；有歧義嘅面參照必須明確修復。'],acceptance:['Edit a bracket’s first sketch, regenerate, undo, save and reopen with equivalent geometry.','修改支架最初嘅草圖、重新計算、復原、儲存再開啟，幾何結果保持一致。'],phase:2},
{id:'assemblies',icon:Component,title:['Assemblies & drawings','組件與工程圖'],summary:['From individual parts to the whole picture.','由單一零件到完整設計。'],body:['Planned reusable components, mates, joint limits, interference checks, exploded views and bills of materials. Associative drawings will provide projected, section and detail views, dimensions, tolerances and title blocks.','規劃包括可重用零件、配合、關節限制、干涉檢查、爆炸圖同物料清單。關聯工程圖會提供投影、剖面、詳圖、尺寸、公差同圖框。'],acceptance:['Update a source part and verify instances, mates, drawings and the bill of materials.','更新來源零件，核對實例、配合、工程圖同物料清單。'],phase:3},
{id:'sheet-metal',icon:Layers3,title:['Sheet metal','鈑金設計'],summary:['Keep folded and flat designs connected.','摺合與展開設計保持連繫。'],body:['Constant-thickness parts, flanges, bends, bend allowances, unfolding and refolding are planned. Flat-pattern exports preserve declared units and bend settings. Unsupported geometry must be diagnosed rather than producing a guessed pattern.','規劃包括等厚零件、凸緣、折彎、折彎餘量、展開同重新摺合。平面圖輸出保留單位同折彎設定；不支援嘅幾何會清楚指出。'],acceptance:['Unfold and refold an enclosure while preserving thickness, dimensions and bend settings.','將外殼展開再摺合，保持厚度、尺寸同折彎設定。'],phase:3},
{id:'cam',icon:Ruler,title:['Manufacturing','製造加工'],summary:['A deliberate path from geometry to machining.','由幾何到加工，每一步都有根據。'],body:['Initial CAM scope: 2.5D and three-axis milling, stock, work coordinates, tools, facing, pockets, profiles and drilling. Revision-bound toolpaths must be simulated and exported through documented postprocessors. Connected-machine control is excluded.','首階段 CAM 包括 2.5D 同三軸銑削、毛坯、工件座標、刀具、面銑、挖槽、輪廓同鑽孔。刀路綁定來源版本，經模擬後透過有文件記錄嘅後處理器輸出，唔包括直接控制機床。'],acceptance:['Simulate a pocketed part, detect introduced collisions and invalidate toolpaths after geometry changes.','模擬挖槽零件、偵測刻意加入嘅碰撞，幾何改變後將舊刀路標示為過期。'],phase:4},
{id:'analysis',icon:Cpu,title:['Structural analysis','結構分析'],summary:['Results with a traceable numerical foundation.','計算結果有清楚嘅數值依據。'],body:['Linear static and modal studies are planned through Gmsh and CalculiX adapters. Materials, loads, constraints, mesh refinement and convergence comparisons remain explicit. Each result identifies its exact geometry and settings; a stress plot alone is not proof of accuracy.','規劃透過 Gmsh 同 CalculiX 進行線性靜力同模態分析，清楚記錄材料、載荷、約束、網格細化同收斂比較。結果列明所用幾何同設定，有張應力圖唔等於數值準確。'],acceptance:['Compare bar, beam and modal fixtures with analytic solutions and declared tolerances.','以桿、樑同模態案例對照解析解，並列明容許誤差。'],phase:5},
{id:'history',icon:GitBranch,title:['Local Git history','本機 Git 歷史'],summary:['Your design decisions deserve a history.','每個設計決定都值得留低紀錄。'],body:['Planned history separates modelling undo from deliberate Git milestones. Compare parameters, features and geometry, explore branches and restore an earlier design after preserving current work. Geometry conflicts require explicit resolution. Local history does not require a cloud account.','規劃分開建模復原同 Git 里程碑，可以比較參數、特徵同幾何、探索分支，先保留現有工作再還原舊設計。幾何衝突要明確處理，本機歷史唔需要雲端帳戶。'],acceptance:['Compare and restore revisions without losing unsaved work or silently merging conflicts.','比較並還原版本，唔會遺失未儲存工作或偷偷合併衝突。'],phase:1},
{id:'exchange',icon:ArrowUpRight,title:['Open exchange','開放格式交換'],summary:['Useful outside one application.','設計唔限於一套應用程式。'],body:['Planned STEP and IGES geometry, STL and 3MF meshes, DXF drafting and PDF drawings. Native documents preserve editable features. Neutral imports do not claim to restore a proprietary feature tree.','規劃包括 STEP 同 IGES 幾何、STL 同 3MF 網格、DXF 製圖同 PDF 工程圖。原生文件保留可編輯特徵，中性格式匯入唔會聲稱可以還原專有特徵樹。'],acceptance:['Round-trip reference geometry and verify units, placement, topology, dimensions and volume.','匯出再匯入參考幾何，核對單位、位置、拓撲、尺寸同體積。'],phase:3}
];
const stages:{title:Words;detail:Words}[]=[
{title:['A dependable foundation','可靠基礎'],detail:['Native build, transactional documents, save and recovery, geometry workers, local history.','原生建置、交易式文件、儲存與復原、幾何工作程序、本機歷史。']},
{title:['Parametric parts','參數式零件'],detail:['Constrained sketches, solids and surfaces, regeneration and reference repair.','約束草圖、實體與曲面、重新計算同參照修復。']},
{title:['The mechanical suite','機械設計套件'],detail:['Assemblies, associative drawings, sheet metal and neutral-format exchange.','組件、關聯工程圖、鈑金同中性格式交換。']},
{title:['Manufacturing workflows','製造流程'],detail:['CAM setups, toolpaths, simulation and documented G-code export.','CAM 設定、刀路、模擬同有文件記錄嘅 G-code 輸出。']},
{title:['Validated analysis','經驗證嘅分析'],detail:['Meshing, static and modal studies, convergence and reference benchmarks.','網格、靜力與模態分析、收斂同參考基準測試。']},
{title:['Ready to distribute','準備發佈'],detail:['Accessibility, localization, offline documentation, installers and update verification.','無障礙、多語言、離線文件、安裝程式同更新驗證。']}
];
function Action({children,onClick,outlined=false,...props}:{children:React.ReactNode;onClick?:()=>void;outlined?:boolean;[key:string]:unknown}){return createElement(outlined?'md-outlined-button':'md-filled-button',{onClick,...props},<span className="action-label">{children}</span>);}

export default function Home(){
 const [language,setLanguage]=useState<Language>('en');const [dark,setDark]=useState(false);const [section,setSection]=useState('overview');const [selected,setSelected]=useState('modelling');const [query,setQuery]=useState('');const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');const [updated,setUpdated]=useState('');const [pattern,setPattern]=useState(false);const [match,setMatch]=useState('contains');
 const t=(w:Words)=>language==='en'?w[0]:language==='yue'?w[1]:`${w[0]} · ${w[1]}`;
 useEffect(()=>{import('@material/web/all.js').catch(()=>setNotice('Interactive controls could not load. Source links remain available.'));try{const p=JSON.parse(localStorage.getItem('precision-cad-preferences')||'{}');if(['en','yue','both'].includes(p.language))setLanguage(p.language);setDark(p.dark===true);}catch{setNotice('Saved preferences could not be read. Defaults are in use.');}if(build.updatedAt)setUpdated(new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'long'}).format(new Date(build.updatedAt)));const key=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();setSection('documentation');requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('#docs-search')?.focus());}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.lang=language==='yue'?'yue-Hant-HK':'en';},[dark,language]);
 const preference=(l:Language,d:boolean)=>{setLanguage(l);setDark(d);try{localStorage.setItem('precision-cad-preferences',JSON.stringify({language:l,dark:d}));}catch{setNotice(t(['Preferences could not be saved on this device.','無法喺呢部裝置儲存偏好設定。']));}};
 const navigate=(s:string)=>{setSection(s);setMenu(false);window.scrollTo({top:0,behavior:'instant'});};
 const openArticle=(id:string)=>{setSelected(id);navigate('documentation');};
 const article=features.find(a=>a.id===selected)||features[0];
 const filtered=features.filter(a=>{const q=query.trim().toLowerCase();return pattern&&match!=='contains'?a.title.some(v=>match==='starts'?v.toLowerCase().startsWith(q):v.toLowerCase().endsWith(q)):[...a.title,...a.body].join(' ').toLowerCase().includes(q);});
 const exportDocs=()=>{const content='# Precision CAD\n\nDevelopment in progress. Check https://github.com/Ding-Ding-Projects/precision-cad/releases for available development builds and their limitations.\n\n'+features.map(a=>`## ${t(a.title)}\n\n${t(a.body)}\n\nAcceptance: ${t(a.acceptance)}\n`).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='precision-cad-documentation.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(t(['Documentation export prepared. Your browser manages the download.','文件匯出已準備好，由瀏覽器處理下載。']));};
 const nav:[string,Words][]=[['overview',['Overview','概覽']],['documentation',['Documentation','文件']],['roadmap',['Roadmap','路線圖']],['settings',['Preferences','偏好設定']]];
 return <main><a className="skip" href="#content">{t(['Skip to content','跳到內容'])}</a><header className="header"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview');}} aria-label="Precision CAD home"><Box/><span>precision<span className="brand-cad">CAD</span></span></a><nav className={menu?'navigation open':'navigation'} aria-label={t(['Main navigation','主導覽'])}>{nav.map(([id,w])=><Action key={id} outlined className={section===id?'nav-button active':'nav-button'} onClick={()=>navigate(id)} aria-current={section===id?'page':undefined}>{t(w)}</Action>)}</nav><a className="source" aria-label="Precision CAD source code" href={repo} target="_blank" rel="noreferrer"><Github size={18}/><span>{t(['Source','原始碼'])}</span><ArrowUpRight size={15}/></a><Action outlined className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={t(['Toggle navigation','開關導覽'])}>{menu?<X/>:<Menu/>}</Action></header>
 <div className="release-strip"><span className="dot"/><span>{t(['Early development','開發初期'])}</span><span className="divider"/><span>{t(['Website','網站'])} {build.version}</span><span className="build-date">{t(['Updated','更新'])}: {updated||`${build.updatedAt} (UTC)`}</span></div><div id="content" tabIndex={-1}>
 {section==='overview'&&<><section className="hero width"><div><span className="eyebrow"><i/>{t(['OPEN-SOURCE ENGINEERING','開源工程設計'])}</span><h1>{t(['Make every','每個設計'])}<br/><em>{t(['dimension count.','都有根據。'])}</em></h1><p className="lead">{t(['A new home for precise mechanical design. Parametric CAD, manufacturing, and structural analysis, with your project history in your hands.','為精準機械設計建立新工作空間。參數式 CAD、製造同結構分析，專案歷史由你掌握。'])}</p><div className="actions"><Action onClick={()=>navigate('roadmap')}>{t(['Explore the roadmap','瀏覽路線圖'])}<ArrowRight size={17}/></Action><Action outlined onClick={()=>navigate('documentation')}>{t(['Read the docs','閱讀文件'])}<BookOpen size={17}/></Action></div><p className="honesty"><span className="dot"/>{t(['Early development. Check release notes before using a development build.','開發初期，使用開發版本前請先閱讀發行說明。'])}</p></div>
 <div className="drawing"><div className="drawing-header"><span>REF. 001 / {t(['MECHANICAL BRACKET','機械支架'])}</span><span>mm</span></div><svg viewBox="0 0 580 400" role="img" aria-label={t(['Illustrative dimensioned orthographic bracket drawing, not output from the CAD application.','支架尺寸正投影示意圖，並非 CAD 應用程式輸出。'])}><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="currentColor" strokeWidth=".4" opacity=".22"/></pattern><marker id="arr" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto-start-reverse"><path d="M0 0L6 3L0 6Z" fill="currentColor"/></marker></defs><rect width="580" height="400" fill="url(#grid)"/><g fill="none" stroke="currentColor"><path d="M110 102H410Q430 102 430 122V242Q430 262 410 262H110Q90 262 90 242V122Q90 102 110 102Z" strokeWidth="2"/><path d="M90 219H430M90 231H430" strokeWidth="1.4"/><circle cx="140" cy="151" r="18" strokeWidth="2"/><circle cx="380" cy="151" r="18" strokeWidth="2"/><rect x="217" y="133" width="86" height="36" rx="18" strokeWidth="2"/><path d="M112 151H168M140 123V179M352 151H408M380 123V179M198 151H322" strokeDasharray="9 4 2 4" opacity=".55"/><path d="M90 81V53M430 81V53M90 63H430M456 102H486M456 262H486M476 102V262M90 277V308M140 188V308M90 299H140" strokeWidth=".8"/><path d="M96 63H424M476 108V256M96 299H134" markerStart="url(#arr)" markerEnd="url(#arr)" strokeWidth=".8"/><path d="M380 151L436 81H516M119 335H406V348H119ZM119 335V320H135V335" strokeWidth="1.2"/></g><g fill="currentColor" fontFamily="monospace" fontSize="14"><text x="260" y="53" textAnchor="middle">120.00</text><text x="490" y="186">56.00</text><text x="115" y="318" textAnchor="middle">18.00</text><text x="445" y="73">2 × Ø12</text><text x="267" y="380" textAnchor="middle" fontSize="11">FRONT / SECTION A</text></g></svg><div className="drawing-footer"><span>+ {t(['DESIGN INTENT','設計意圖'])}</span><span>{t(['Concept drawing · not a product capture','概念圖 · 並非產品畫面'])}</span></div></div></section>
 <div className="principles width">{([['Precision first','精準優先'],['Local by design','以本機為核心'],['History you own','歷史由你掌握'],['Open foundations','開放技術基礎']] as Words[]).map((w,i)=><div key={i}><span>0{i+1}</span>{t(w)}</div>)}</div>
 <section className="features width"><div className="section-heading"><div><span className="eyebrow">{t(['THE PLANNED TOOLSET','規劃中嘅工具'])}</span><h2>{t(['One connected engineering workflow.','連貫嘅工程設計流程。'])}</h2></div><p>{t(['From the first constraint to the final drawing. Each workbench is planned around the same editable design.','由第一個約束到最後一張工程圖，各工作台圍繞同一個可編輯設計。'])}</p></div><div className="feature-grid">{features.slice(0,6).map((a,i)=><article className="feature-card" key={a.id}><div className="feature-top"><a.icon size={26} strokeWidth={1.5}/><span>0{i+1}</span></div><span className="planned">{t(['Planned','規劃中'])}</span><h3>{t(a.title)}</h3><p>{t(a.summary)}</p><Action outlined className="text-button" onClick={()=>openArticle(a.id)}>{t(['Read the specification','閱讀規格'])}<ArrowUpRight size={16}/></Action></article>)}</div></section>
 <section className="history-section"><div className="width history-grid"><div><span className="eyebrow">{t(['A RECORD OF YOUR REASONING','設計思路有紀錄'])}</span><h2>{t(['Change your mind.','改變主意。'])}<br/>{t(['Keep your history.','保留歷史。'])}</h2><p>{t(['Planned local Git integration makes meaningful revisions part of the workflow. Compare a design, explore a branch, or return to an earlier decision while preserving your current work.','規劃中嘅本機 Git 整合會將重要版本納入工作流程，比較設計、探索分支，或者重返先前決定，同時保留現有工作。'])}</p><Action outlined onClick={()=>openArticle('history')}>{t(['How history will work','了解歷史管理'])}<ArrowRight size={16}/></Action></div><div className="history-example"><span className="eyebrow">{t(['ILLUSTRATIVE REVISION FLOW','版本流程示例'])}</span>{([['Refine the mounting holes','調整安裝孔'],['Explore a lighter profile','探索更輕巧輪廓'],['Establish the first design','建立初始設計']] as Words[]).map((w,i)=><div className="revision" key={i}><i/><span className="mono">0{3-i}</span><span>{t(w)}</span><GitBranch size={17}/></div>)}<p className="example-note">{t(['Example only. The desktop history manager is not implemented yet.','只作示例，桌面歷史管理器尚未實作。'])}</p></div></div></section>
 <section className="open-section width"><div><span className="eyebrow">{t(['BUILT IN THE OPEN','開放開發'])}</span><h2>{t(['Follow the work.','追蹤開發。'])}<br/>{t(['See what comes next.','了解下一步。'])}</h2></div><div><p>{t(['The architecture and roadmap are available now. The native application is at the foundation stage; modelling, machining and analysis are future milestones, not shipped tools.','架構同路線圖現已公開。原生應用程式處於基礎階段，建模、加工同分析係未來里程碑，並非已交付工具。'])}</p><div className="actions"><a className="link-pill" href={repo} target="_blank" rel="noreferrer">{t(['View the repository','查看原始碼專案'])}<ArrowUpRight size={17}/></a><Action outlined onClick={()=>navigate('roadmap')}>{t(['Delivery milestones','交付里程碑'])}</Action></div></div></section></>}
 {section==='documentation'&&<section className="width inner-page"><span className="eyebrow">{t(['PROJECT KNOWLEDGE','專案知識'])}</span><div className="section-heading"><h1>{t(['Documentation','文件'])}</h1><Action outlined onClick={exportDocs}><Download size={17}/>{t(['Export documentation','匯出文件'])}</Action></div><p className="page-intro">{t(['Design specifications and acceptance criteria. These describe the intended product, not currently available desktop features.','設計規格同驗收準則，描述目標產品，並非目前已提供嘅桌面功能。'])}</p><div className="docs-grid"><aside><label htmlFor="docs-search">{t(['Find a feature','搜尋功能'])}</label><div className="search-box"><Search size={17}/><input id="docs-search" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)} placeholder={t(['Search documentation','搜尋文件'])}/></div><Action outlined className="text-button" onClick={()=>setPattern(!pattern)} aria-expanded={pattern}>{t(['Match options','比對選項'])}</Action>{pattern&&<div className="pattern"><p>{t(['Literal text matching. Choose where the feature title must match.','文字比對，可選功能標題比對位置。'])}</p>{(['contains','starts','ends'] as const).map((v,i)=><Action key={v} outlined onClick={()=>setMatch(v)} aria-pressed={match===v}>{t(([['Contains text','包含文字'],['Title starts with','標題開頭'],['Title ends with','標題結尾']] as Words[])[i])}</Action>)}</div>}<nav className="docs-nav" aria-label={t(['Feature articles','功能文章'])}>{filtered.map(a=><Action key={a.id} outlined className={selected===a.id?'doc-link selected':'doc-link'} onClick={()=>setSelected(a.id)}><a.icon size={17}/>{t(a.title)}</Action>)}</nav>{!filtered.length&&<p role="status">{t(['No matching articles.','冇符合文章。'])}</p>}</aside><article className="doc-article"><span className="planned">{t(['Planned capability','規劃中功能'])} / {t(['Phase','階段'])} 0{article.phase}</span><h2>{t(article.title)}</h2><p className="article-lead">{t(article.summary)}</p><p>{t(article.body)}</p><h3>{t(['What will count as working','點樣先算完成'])}</h3><div className="acceptance"><Check size={21}/><p>{t(article.acceptance)}</p></div><h3>{t(['Current availability','目前狀態'])}</h3><p>{t(['Not implemented in the desktop application. Follow the tracked roadmap for implementation and verification evidence. Do not rely on planned functionality for production work.','桌面應用程式尚未實作，請查看路線圖追蹤實作同驗證證據，唔好依賴規劃中功能進行生產工作。'])}</p><h3>{t(['Related specifications','相關規格'])}</h3><div className="related">{features.filter(a=>a.id!==article.id).slice(0,3).map(a=><Action key={a.id} outlined onClick={()=>setSelected(a.id)}>{t(a.title)}<ArrowRight size={15}/></Action>)}</div><a className="inline-link" href={`${repo}/blob/main/docs/engineering/architecture.md`}>{t(['Read the technical architecture','閱讀技術架構'])}<ArrowUpRight size={16}/></a></article></div></section>}
 {section==='roadmap'&&<section className="width inner-page"><span className="eyebrow">{t(['BUILDING WITH INTENT','有目標地建立'])}</span><h1>{t(['The road to precision.','通往精準之路。'])}</h1><p className="page-intro">{t(['Six delivery stages. Each must demonstrate real behaviour before it is marked complete. There is no announced release date.','六個交付階段，每個都要展示真實功能先會標示完成，暫時未有公佈發行日期。'])}</p><div className="roadmap-list">{stages.map((s,i)=><article className="roadmap-row" key={i}><span className="roadmap-number">0{i+1}</span><div><h2>{t(s.title)}</h2><p>{t(s.detail)}</p></div><span className={i===0?'phase-status current':'phase-status'}>{i===0?t(['In progress','進行中']):t(['Planned','規劃中'])}</span></article>)}</div><div className="scope-note"><h3>{t(['A clear first-release boundary','清楚嘅首次發行範圍'])}</h3><p>{t(['Windows x64. No native proprietary CAD import, turning, five-axis machining, nonlinear or fluid simulation, cloud collaboration, or connected-machine control in this release.','Windows x64。首次發行唔包括原生專有 CAD 匯入、車削、五軸加工、非線性或流體模擬、雲端協作及直接控制機床。'])}</p><a className="inline-link" href={`${repo}/blob/main/ROADMAP.md`}>{t(['Open the tracked checklist','開啟追蹤清單'])}<ArrowUpRight size={16}/></a></div></section>}
 {section==='settings'&&<section className="width inner-page preferences"><span className="eyebrow">{t(['MAKE IT YOURS','按你喜好'])}</span><h1>{t(['Reading preferences','閱讀偏好'])}</h1><p className="page-intro">{t(['These preferences stay in this browser. They do not change a CAD project or send information to a server.','偏好只留喺瀏覽器，唔會更改 CAD 專案或將資料傳送到伺服器。'])}</p><div className="setting-row"><div><h2>{t(['Appearance','外觀'])}</h2><p>{t(['Choose a light or dark reading surface.','選擇淺色或深色閱讀畫面。'])}</p></div><div className="choices"><Action outlined aria-pressed={!dark} onClick={()=>preference(language,false)}><Sun size={18}/>{t(['Light','淺色'])}</Action><Action outlined aria-pressed={dark} onClick={()=>preference(language,true)}><Moon size={18}/>{t(['Dark','深色'])}</Action></div></div><div className="setting-row"><div><h2>{t(['Language','語言'])}</h2><p>{t(['English, Cantonese, or both together.','英文、廣東話或雙語。'])}</p></div><div className="choices">{(['en','yue','both'] as Language[]).map(l=><Action key={l} outlined aria-pressed={language===l} onClick={()=>preference(l,dark)}>{l==='en'?'English':l==='yue'?'廣東話':'Bilingual · 雙語'}</Action>)}</div></div><div className="setting-row"><div><h2>{t(['Reset preferences','重設偏好'])}</h2><p>{t(['Return to English and the light theme.','返回英文同淺色主題。'])}</p></div><Action outlined onClick={()=>{preference('en',false);setNotice('Reading preferences reset.');}}>{t(['Reset','重設'])}</Action></div></section>}
 </div>{notice&&<div className="notice" role="status"><span>{notice}</span><Action outlined onClick={()=>setNotice('')} aria-label={t(['Dismiss notification','關閉通知'])}><X size={16}/></Action></div>}<footer className="footer width"><div className="brand"><Box size={26}/><span>precision<span className="brand-cad">CAD</span></span></div><span>{t(['Open source. Clear intent. Work in progress.','開放原始碼，清楚設計意圖，持續開發中。'])}</span><a href={`${repo}/blob/main/ROADMAP.md`}>{t(['Development status','開發狀態'])}<ArrowUpRight size={15}/></a></footer></main>;
}
