cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  project(PrecisionHistory LANGUAGES CXX)
  enable_testing()
endif()
find_package(Qt6 6.8 REQUIRED COMPONENTS Core)
qt_standard_project_setup()
qt_add_library(precision_history STATIC local_history_service.cpp)
target_compile_features(precision_history PUBLIC cxx_std_20)
target_link_libraries(precision_history PUBLIC Qt6::Core)
target_include_directories(precision_history PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/..)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
  add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../tests/history ${CMAKE_CURRENT_BINARY_DIR}/tests)
endif()
