#include "GeometryWorker.h"
#include <QCoreApplication>
#include <QJsonArray>
#include <QJsonObject>
#include <QtTest/QTest>

using precision::geometry::executeRequest;
class GeometryWorkerTests final : public QObject {
  Q_OBJECT
  QJsonObject request(const QString& operation, QJsonObject parameters) { return {{"protocolVersion", 1}, {"operationId", "op-1"}, {"documentId", "doc-1"}, {"revision", 7}, {"operation", operation}, {"parameters", parameters}}; }
private slots:
  void primitiveVolumesAndTessellation() { const auto reply = executeRequest(request("box", {{"dx", 10.0}, {"dy", 20.0}, {"dz", 30.0}})); QVERIFY(reply.value("ok").toBool()); const auto result = reply.value("result").toObject(); QCOMPARE(result.value("volume").toDouble(), 6000.0); QVERIFY(!result.value("brep").toString().isEmpty()); QVERIFY(result.value("mesh").toObject().value("indices").toArray().size() >= 36); }
  void drilledBracketBoolean() { const auto box = executeRequest(request("box", {{"dx", 20.0}, {"dy", 20.0}, {"dz", 10.0}})).value("result").toObject().value("brep").toString(); const auto hole = executeRequest(request("cylinder", {{"radius", 4.0}, {"height", 10.0}, {"origin", QJsonArray{10.0, 10.0, 0.0}}})).value("result").toObject().value("brep").toString(); const auto result = executeRequest(request("cut", {{"leftBrep", box}, {"rightBrep", hole}})); QVERIFY(result.value("ok").toBool()); QVERIFY(result.value("result").toObject().value("volume").toDouble() < 4000.0); }
  void serializationRoundTrip() { const auto first = executeRequest(request("cylinder", {{"radius", 2.0}, {"height", 10.0}})); const auto encoded = first.value("result").toObject().value("brep").toString(); const auto second = executeRequest(request("validate", {{"brep", encoded}})); QVERIFY(second.value("ok").toBool()); QCOMPARE(second.value("result").toObject().value("volume").toDouble(), first.value("result").toObject().value("volume").toDouble()); }
  void cylinderNormalsAndWinding() { const auto result = executeRequest(request("cylinder", {{"radius", 2.0}, {"height", 6.0}})).value("result").toObject().value("mesh").toObject(); const auto vertices = result.value("vertices").toArray(), normals = result.value("normals").toArray(), indices = result.value("indices").toArray(); QVERIFY(vertices.size() == normals.size()); bool radial = false; for (int i = 0; i < vertices.size(); i += 3) { const double x = vertices.at(i).toDouble(), y = vertices.at(i + 1).toDouble(), nz = normals.at(i + 2).toDouble(); if (x*x + y*y > 3.5 && std::abs(nz) < 0.2) { const double dot = (x * normals.at(i).toDouble() + y * normals.at(i + 1).toDouble()) / std::sqrt(x*x+y*y); QVERIFY(dot > 0.9); radial = true; } } QVERIFY(radial); for (int i = 0; i < indices.size(); i += 3) { const int ia = indices.at(i).toInt(), ib = indices.at(i+1).toInt(), ic = indices.at(i+2).toInt(); const auto p = [&vertices](int n, int c) { return vertices.at(n*3+c).toDouble(); }; const double ux=p(ib,0)-p(ia,0), uy=p(ib,1)-p(ia,1), uz=p(ib,2)-p(ia,2), vx=p(ic,0)-p(ia,0), vy=p(ic,1)-p(ia,1), vz=p(ic,2)-p(ia,2); const double nx=normals.at(ia*3).toDouble()+normals.at(ib*3).toDouble()+normals.at(ic*3).toDouble(), ny=normals.at(ia*3+1).toDouble()+normals.at(ib*3+1).toDouble()+normals.at(ic*3+1).toDouble(), nz=normals.at(ia*3+2).toDouble()+normals.at(ib*3+2).toDouble()+normals.at(ic*3+2).toDouble(); QVERIFY((uy*vz-uz*vy)*nx+(uz*vx-ux*vz)*ny+(ux*vy-uy*vx)*nz > 0.0); } }
  void rejectsUnknownAndInvalid() { QVERIFY(!executeRequest(request("teleport", {})).value("ok").toBool()); QVERIFY(!executeRequest(request("box", {{"dx", -1.0}, {"dy", 1.0}, {"dz", 1.0}})).value("ok").toBool()); auto incompatible = request("box", {{"dx", 1.0}, {"dy", 1.0}, {"dz", 1.0}}); incompatible.insert("protocolVersion", 1.5); QVERIFY(!executeRequest(incompatible).value("ok").toBool()); const auto box = executeRequest(request("box", {{"dx", 1.0}, {"dy", 1.0}, {"dz", 1.0}})).value("result").toObject().value("brep").toString(); QVERIFY(!executeRequest(request("validate", {{"brep", box + "!"}})).value("ok").toBool()); QVERIFY(executeRequest(request("translate", {{"brep", box}, {"vector", QJsonArray{0.0,0.0,0.0}}})).value("ok").toBool()); }
};
QTEST_MAIN(GeometryWorkerTests)
#include "GeometryWorkerTests.moc"
