#include "GeometryWorker.h"
#include <QCoreApplication>
#include <QJsonArray>
#include <QJsonObject>
#include <QSet>
#include <QtTest/QTest>

using precision::geometry::executeRequest;
class GeometryWorkerTests final : public QObject {
  Q_OBJECT
  QJsonObject request(const QString& operation, QJsonObject parameters) { return {{"protocolVersion", 1}, {"operationId", "op-1"}, {"documentId", "doc-1"}, {"revision", 7}, {"operation", operation}, {"parameters", parameters}}; }
  QJsonObject topologyRequest(double dx, double dy, double dz) { auto value = request("box", {{"dx", dx}, {"dy", dy}, {"dz", dz}}); value.insert("topologyVersion", 1); value.insert("producerFeatureId", "123e4567-e89b-42d3-a456-426614174000"); return value; }
private slots:
  void primitiveVolumesAndTessellation() { const auto reply = executeRequest(request("box", {{"dx", 10.0}, {"dy", 20.0}, {"dz", 30.0}})); QVERIFY(reply.value("ok").toBool()); const auto result = reply.value("result").toObject(); QCOMPARE(result.value("volume").toDouble(), 6000.0); QVERIFY(!result.value("brep").toString().isEmpty()); QVERIFY(result.value("mesh").toObject().value("indices").toArray().size() >= 36); QVERIFY(executeRequest(request("box", {{"dx", 2000.0}, {"dy", 2000.0}, {"dz", 2000.0}})).value("ok").toBool()); }
  void drilledBracketBoolean() { const auto box = executeRequest(request("box", {{"dx", 20.0}, {"dy", 20.0}, {"dz", 10.0}})).value("result").toObject().value("brep").toString(); const auto hole = executeRequest(request("cylinder", {{"radius", 4.0}, {"height", 10.0}, {"origin", QJsonArray{10.0, 10.0, 0.0}}})).value("result").toObject().value("brep").toString(); const auto result = executeRequest(request("cut", {{"leftBrep", box}, {"rightBrep", hole}})); QVERIFY(result.value("ok").toBool()); QVERIFY(result.value("result").toObject().value("volume").toDouble() < 4000.0); }
  void serializationRoundTrip() { const auto first = executeRequest(request("cylinder", {{"radius", 2.0}, {"height", 10.0}})); const auto encoded = first.value("result").toObject().value("brep").toString(); const auto second = executeRequest(request("validate", {{"brep", encoded}})); QVERIFY(second.value("ok").toBool()); QCOMPARE(second.value("result").toObject().value("volume").toDouble(), first.value("result").toObject().value("volume").toDouble()); }
  void cylinderNormalsAndWinding() { const auto result = executeRequest(request("cylinder", {{"radius", 2.0}, {"height", 6.0}})).value("result").toObject().value("mesh").toObject(); const auto vertices = result.value("vertices").toArray(), normals = result.value("normals").toArray(), indices = result.value("indices").toArray(); QVERIFY(vertices.size() == normals.size()); bool radial = false; for (int i = 0; i < vertices.size(); i += 3) { const double x = vertices.at(i).toDouble(), y = vertices.at(i + 1).toDouble(), nz = normals.at(i + 2).toDouble(); if (x*x + y*y > 3.5 && std::abs(nz) < 0.2) { const double dot = (x * normals.at(i).toDouble() + y * normals.at(i + 1).toDouble()) / std::sqrt(x*x+y*y); QVERIFY(dot > 0.9); radial = true; } } QVERIFY(radial); for (int i = 0; i < indices.size(); i += 3) { const int ia = indices.at(i).toInt(), ib = indices.at(i+1).toInt(), ic = indices.at(i+2).toInt(); const auto p = [&vertices](int n, int c) { return vertices.at(n*3+c).toDouble(); }; const double ux=p(ib,0)-p(ia,0), uy=p(ib,1)-p(ia,1), uz=p(ib,2)-p(ia,2), vx=p(ic,0)-p(ia,0), vy=p(ic,1)-p(ia,1), vz=p(ic,2)-p(ia,2); const double nx=normals.at(ia*3).toDouble()+normals.at(ib*3).toDouble()+normals.at(ic*3).toDouble(), ny=normals.at(ia*3+1).toDouble()+normals.at(ib*3+1).toDouble()+normals.at(ic*3+1).toDouble(), nz=normals.at(ia*3+2).toDouble()+normals.at(ib*3+2).toDouble()+normals.at(ic*3+2).toDouble(); QVERIFY((uy*vz-uz*vy)*nx+(uz*vx-ux*vz)*ny+(ux*vy-uy*vx)*nz > 0.0); } }
  void topologyOptInMapsEveryTriangleToAnExistingFace() { const auto standard = executeRequest(request("box", {{"dx", 10.0}, {"dy", 20.0}, {"dz", 30.0}})); QVERIFY(!standard.value("result").toObject().contains("topology")); const auto topology = executeRequest(topologyRequest(10.0, 20.0, 30.0)).value("result").toObject().value("topology").toObject(); QCOMPARE(topology.value("version").toInt(), 1); const auto triangleFaceIds = topology.value("triangleFaceIds").toArray(), indices = executeRequest(topologyRequest(10.0, 20.0, 30.0)).value("result").toObject().value("mesh").toObject().value("indices").toArray(); QCOMPARE(triangleFaceIds.size(), indices.size()/3); QSet<int> faces; for (const auto& entity : topology.value("entities").toArray()) { const auto object = entity.toObject(); if (object.value("source").toObject().value("entityKind") == "face") faces.insert(object.value("id").toInt()); } QVERIFY(!faces.isEmpty()); for (const auto& id : triangleFaceIds) QVERIFY(faces.contains(id.toInt())); QVERIFY(!topology.value("edgePolylines").toArray().isEmpty()); }
  void primitiveTopologyKeysRemainSemanticWhenDimensionsChange() { const auto first = executeRequest(topologyRequest(10.0, 20.0, 30.0)).value("result").toObject().value("topology").toObject(); const auto second = executeRequest(topologyRequest(11.0, 20.0, 30.0)).value("result").toObject().value("topology").toObject(); QJsonObject firstFace, secondFace; for (const auto& entity : first.value("entities").toArray()) if (entity.toObject().value("source").toObject().value("key") == "box.face.xmax") firstFace = entity.toObject(); for (const auto& entity : second.value("entities").toArray()) if (entity.toObject().value("source").toObject().value("key") == "box.face.xmax") secondFace = entity.toObject(); QVERIFY(!firstFace.isEmpty()); QVERIFY(!secondFace.isEmpty()); QVERIFY(firstFace.value("source").toObject().value("signature") != secondFace.value("source").toObject().value("signature")); }
  void resolverRejectsSymmetricSignatureAmbiguity() { const QJsonArray entities{QJsonObject{{"id", 1}, {"source", QJsonObject{{"featureId", "f1"}, {"entityKind", "edge"}, {"signature", QJsonObject{{"kind", "edge"}}}}}}, QJsonObject{{"id", 2}, {"source", QJsonObject{{"featureId", "f1"}, {"entityKind", "edge"}, {"signature", QJsonObject{{"kind", "edge"}}}}}}}; QCOMPARE(precision::geometry::resolveTopologyReference(entities, QJsonObject{{"featureId", "f1"}, {"entityKind", "edge"}, {"signature", QJsonObject{{"kind", "edge"}}}}).value("status").toString(), "ambiguous"); }
  void filletKeepsLegacyCompatibilityAndRejectsBadSelectedTopology() { const auto box = executeRequest(request("box", {{"dx", 10.0}, {"dy", 20.0}, {"dz", 30.0}})).value("result").toObject().value("brep").toString(); QVERIFY(executeRequest(request("fillet", {{"brep", box}, {"radius", 1.0}})).value("ok").toBool()); QJsonObject selected{{"version",1},{"mode","selectedEdges"},{"producerFeatureId","123e4567-e89b-42d3-a456-426614174000"},{"producerOperation","box"},{"brepSha256","wrong"},{"edgeRefs",QJsonArray{}}}; QVERIFY(!executeRequest(request("fillet", {{"brep", box}, {"radius", 1.0}, {"topologyInput", selected}})).value("ok").toBool()); }
  void rejectsUnknownAndInvalid() { QVERIFY(!executeRequest(request("teleport", {})).value("ok").toBool()); QVERIFY(!executeRequest(request("box", {{"dx", -1.0}, {"dy", 1.0}, {"dz", 1.0}})).value("ok").toBool()); auto incompatible = request("box", {{"dx", 1.0}, {"dy", 1.0}, {"dz", 1.0}}); incompatible.insert("protocolVersion", 1.5); QVERIFY(!executeRequest(incompatible).value("ok").toBool()); const auto box = executeRequest(request("box", {{"dx", 1.0}, {"dy", 1.0}, {"dz", 1.0}})).value("result").toObject().value("brep").toString(); QVERIFY(!executeRequest(request("validate", {{"brep", box + "!"}})).value("ok").toBool()); QVERIFY(executeRequest(request("translate", {{"brep", box}, {"vector", QJsonArray{0.0,0.0,0.0}}})).value("ok").toBool()); }
};
QTEST_MAIN(GeometryWorkerTests)
#include "GeometryWorkerTests.moc"
