#include "sketch_model.h"
#include "sketch_profiles.h"
#include <QCoreApplication>
#include <algorithm>
#include <cstdlib>
#include <cstdio>
#include <cmath>

using namespace precision::sketch;
static int assertions=0;
#define REQUIRE(x) do { ++assertions; if(!(x)) { std::fprintf(stderr,"FAIL %s:%d: %s\n",__FILE__,__LINE__,#x); return 1; } } while(false)
static SketchEntity point(SketchEntityId id,double u,double v) { SketchEntity e; e.id=id;e.kind=SketchEntityKind::Point;e.u=u;e.v=v;return e; }
static SketchEntity line(SketchEntityId id,SketchEntityId a,SketchEntityId b) { SketchEntity e; e.id=id;e.kind=SketchEntityKind::Line;e.startPointId=a;e.endPointId=b;return e; }
static SketchEntity circle(SketchEntityId id,SketchEntityId c,double r) { SketchEntity e; e.id=id;e.kind=SketchEntityKind::Circle;e.centerPointId=c;e.radius=r;return e; }
static SketchConstraint c(SketchConstraintId id,SketchConstraintKind k,SketchEntityId a,SketchEntityId b=0,double v=0) { return {id,k,{},a,b,v}; }
static SketchModel rectangleHole() { SketchModel m; m.id="rectangle-hole"; m.entities={point(1,0,0),point(2,80,0),point(3,80,40),point(4,0,40),point(5,40,20),circle(6,5,8),line(10,1,2),line(11,2,3),line(12,3,4),line(13,4,1)}; m.constraints={c(1,SketchConstraintKind::Fixed,1),c(2,SketchConstraintKind::Distance,1,2,80),c(3,SketchConstraintKind::Distance,2,3,40),c(4,SketchConstraintKind::Fixed,5),c(5,SketchConstraintKind::Horizontal,10),c(6,SketchConstraintKind::Vertical,11),c(7,SketchConstraintKind::Horizontal,12),c(8,SketchConstraintKind::Vertical,13),c(9,SketchConstraintKind::Radius,6,0,8)}; return m; }
static SketchModel scaledRectangle(double x,double y,double width,double height,double holeRadius) { auto m=rectangleHole(); m.id=QStringLiteral("scaled-%1-%2").arg(x).arg(width); m.entities[0]=point(1,x,y); m.entities[1]=point(2,x+width,y); m.entities[2]=point(3,x+width,y+height); m.entities[3]=point(4,x,y+height); m.entities[4]=point(5,x+width/2,y+height/2); m.entities[5]=circle(6,5,holeRadius); m.constraints[1].value=width; m.constraints[2].value=height; m.constraints.back().value=holeRadius; return m; }
static QString signature(const SketchProfileResult&r) { QStringList rows; for(const auto&loop:r.loops) { QStringList segments; for(const auto&s:loop.segments) segments << QStringLiteral("%1:%2:%3").arg(s.sourceEntityId).arg(s.startPointId).arg(s.endPointId); rows << loop.stableId+QLatin1Char('|')+(loop.clockwise?QStringLiteral("cw"):QStringLiteral("ccw"))+QLatin1Char('|')+segments.join(QLatin1Char(',')); } return rows.join(QLatin1Char(';')); }
static bool has(const SketchProfileResult&r,ProfileDiagnosticKind k) { for(const auto&d:r.diagnostics) if(d.kind==k) return true; return false; }
int main(int argc,char**argv) { QCoreApplication app(argc,argv);
  auto model=rectangleHole(); const auto solved=solveAndExtractProfiles(model); REQUIRE(solved.solve.status==SolveStatus::Solved); const auto first=solved.profiles; REQUIRE(first.valid()); REQUIRE(first.loops.size()==2); REQUIRE(first.regions.size()==1); REQUIRE(first.regions[0].holeLoopIds.size()==1); REQUIRE(first.loops[0].segments[0].sourceEntityId!=0); REQUIRE(first.loops[0].segments[0].kind==ProfileCurveKind::Circle || first.loops[0].segments[0].kind==ProfileCurveKind::Line); const auto loopById=[&](const QString&id)->const SketchProfileLoop& { for(const auto&loop:first.loops) if(loop.stableId==id) return loop; std::abort(); }; REQUIRE(!loopById(first.regions[0].outerLoopId).clockwise); REQUIRE(loopById(first.regions[0].holeLoopIds[0]).clockwise);
  const auto ids=first.loops; model.constraints[1].value=100; const auto changed=solveAndExtractProfiles(model); REQUIRE(changed.solve.status==SolveStatus::Solved); const auto second=changed.profiles; REQUIRE(second.valid()); REQUIRE(second.loops.size()==ids.size()); REQUIRE(second.loops[0].stableId==ids[0].stableId); REQUIRE(second.loops[1].stableId==ids[1].stableId);
  auto open=rectangleHole(); open.entities.removeLast(); open.constraints.removeAt(7); auto openResult=solveAndExtractProfiles(open).profiles; REQUIRE(!openResult.valid()); REQUIRE(has(openResult,ProfileDiagnosticKind::Dangling));
  auto branch=rectangleHole(); branch.entities.push_back(point(7,0,20)); branch.entities.push_back(line(14,4,7)); branch.constraints.push_back(c(20,SketchConstraintKind::Fixed,7)); auto branchResult=solveAndExtractProfiles(branch).profiles; REQUIRE(!branchResult.valid()); REQUIRE(has(branchResult,ProfileDiagnosticKind::Branched));
  auto crossing=rectangleHole(); crossing.entities.push_back(line(14,1,3)); crossing.entities.push_back(line(15,2,4)); auto crossResult=solveAndExtractProfiles(crossing).profiles; REQUIRE(!crossResult.valid()); REQUIRE(has(crossResult,ProfileDiagnosticKind::Branched));
  auto touching=rectangleHole(); touching.entities[5].radius=20; touching.constraints.back().value=20; auto touchResult=solveAndExtractProfiles(touching).profiles; REQUIRE(!touchResult.valid()); REQUIRE(has(touchResult,ProfileDiagnosticKind::Touching));
  auto island=rectangleHole(); island.entities.push_back(point(7,40,20)); island.entities.push_back(circle(20,7,3)); island.constraints.push_back(c(20,SketchConstraintKind::Fixed,7)); island.constraints.push_back(c(21,SketchConstraintKind::Radius,20,0,3)); const auto islandResult=solveAndExtractProfiles(island); REQUIRE(islandResult.solve.status==SolveStatus::Solved); REQUIRE(islandResult.profiles.valid()); REQUIRE(islandResult.profiles.regions.size()==2); REQUIRE(islandResult.profiles.regions[0].holeLoopIds.size()+islandResult.profiles.regions[1].holeLoopIds.size()==1);
  SketchModel circleOuter; circleOuter.id="circle-outer-square-hole-island"; circleOuter.entities={point(1,0,0),point(2,-20,-20),point(3,20,-20),point(4,20,20),point(5,-20,20),point(6,0,0),circle(10,1,100),line(20,2,3),line(21,3,4),line(22,4,5),line(23,5,2),circle(30,6,5)}; for(SketchEntityId id=1;id<=6;++id) circleOuter.constraints.push_back(c(id,SketchConstraintKind::Fixed,id)); circleOuter.constraints.push_back(c(40,SketchConstraintKind::Radius,10,0,100)); circleOuter.constraints.push_back(c(41,SketchConstraintKind::Radius,30,0,5)); const auto outerResult=solveAndExtractProfiles(circleOuter); REQUIRE(outerResult.solve.status==SolveStatus::Solved); REQUIRE(outerResult.profiles.valid()); REQUIRE(outerResult.profiles.regions.size()==2); REQUIRE(outerResult.profiles.regions[0].holeLoopIds.size()+outerResult.profiles.regions[1].holeLoopIds.size()==1);
  auto crossingCircle=rectangleHole(); crossingCircle.entities[4]=point(5,40,0); crossingCircle.entities[5]=circle(6,5,8); auto crossingCircleResult=solveAndExtractProfiles(crossingCircle).profiles; REQUIRE(!crossingCircleResult.valid()); REQUIRE(has(crossingCircleResult,ProfileDiagnosticKind::Touching));
  auto tangentCircle=rectangleHole(); tangentCircle.entities[4]=point(5,40,-8); tangentCircle.entities[5]=circle(6,5,8); auto tangentCircleResult=solveAndExtractProfiles(tangentCircle).profiles; REQUIRE(!tangentCircleResult.valid()); REQUIRE(has(tangentCircleResult,ProfileDiagnosticKind::Touching));
  auto endpointCircle=rectangleHole(); endpointCircle.entities[4]=point(5,8,0); endpointCircle.entities[5]=circle(6,5,8); auto endpointCircleResult=solveAndExtractProfiles(endpointCircle).profiles; REQUIRE(!endpointCircleResult.valid()); REQUIRE(has(endpointCircleResult,ProfileDiagnosticKind::Touching));
  for(const auto &scaled : {scaledRectangle(0,0,8e-4,4e-4,8e-5),scaledRectangle(900000000,0,80,40,8),scaledRectangle(-400000000,-400000000,500000000,300000000,50000000)}) { const auto scaledResult=solveAndExtractProfiles(scaled); REQUIRE(scaledResult.solve.status==SolveStatus::Solved); REQUIRE(scaledResult.profiles.valid()); REQUIRE(scaledResult.profiles.regions.size()==1); }
  auto reordered=rectangleHole(); std::reverse(reordered.entities.begin(),reordered.entities.end()); std::reverse(reordered.constraints.begin(),reordered.constraints.end()); const auto reorderedResult=solveAndExtractProfiles(reordered); REQUIRE(reorderedResult.profiles.valid()); REQUIRE(signature(reorderedResult.profiles)==signature(first)); for(const auto&loop:reorderedResult.profiles.loops) { const auto minimum=std::min_element(loop.segments.cbegin(),loop.segments.cend(),[](const auto&a,const auto&b){return a.sourceEntityId<b.sourceEntityId;}); REQUIRE(loop.segments.size()==1 || loop.segments.front().sourceEntityId==minimum->sourceEntityId); }
  SketchModel bow; bow.id="bow"; bow.entities={point(1,0,0),point(2,20,20),point(3,0,20),point(4,20,0),line(10,1,2),line(11,2,3),line(12,3,4),line(13,4,1)}; bow.constraints={c(1,SketchConstraintKind::Fixed,1),c(2,SketchConstraintKind::Fixed,2),c(3,SketchConstraintKind::Fixed,3),c(4,SketchConstraintKind::Fixed,4)}; const auto bowResult=solveAndExtractProfiles(bow).profiles; REQUIRE(!bowResult.valid()); REQUIRE(has(bowResult,ProfileDiagnosticKind::SelfIntersecting)); REQUIRE(bowResult.loops.isEmpty());
  std::printf("PASS: %d assertions, real solver profile loops, regions, provenance, and topology rejection\n",assertions); return 0;
}
