#include <QtTest>
#include <QTemporaryDir>
#include "workspace_controller.h"
using namespace precision::core;
class WorkspaceControllerTest final : public QObject {
 Q_OBJECT
private:
 void seed(WorkspaceController &c) { c.addBox(10,10,10); QTRY_COMPARE(c.operationState(),QString("Ready")); QCOMPARE(c.features().size(),1); QVERIFY(!c.meshVertices().isEmpty()); }
private slots:
 void init() { qputenv("PRECISION_GEOMETRY_WORKER",QByteArrayLiteral(FAKE_WORKER_PATH)); qunsetenv("PRECISION_WORKER_TIMEOUT_MS"); qunsetenv("PRECISION_WORKER_CACHE_BYTES"); }
 void unavailableWorkerClearsBusy() { WorkspaceController c; seed(c); auto old=c.features(); qputenv("PRECISION_GEOMETRY_WORKER","Z:/missing-worker.exe"); c.addBox(1,1,1); QTRY_COMPARE(c.operationState(),QString("Failed")); QVERIFY(!c.busy()); QCOMPARE(c.features(),old); }
 void invalidDimensions() { WorkspaceController c; seed(c); auto old=c.features(); c.addBox(-1,1,1); QTRY_COMPARE(c.operationState(),QString("Failed")); QCOMPARE(c.features(),old); QVERIFY(!c.busy()); }
 void invalidResults_data() { QTest::addColumn<double>("dx"); for(int i:{11,12,13,15,17,18,19,20,21,22,23,24,25}) QTest::newRow(qPrintable(QString::number(i)))<<double(i); }
 void invalidResults() { QFETCH(double,dx); WorkspaceController c; seed(c); auto old=c.features(),mesh=c.meshVertices(); c.addBox(dx,1,1); QTRY_COMPARE_WITH_TIMEOUT(c.operationState(),QString("Failed"),4000); QVERIFY(!c.busy()); QCOMPARE(c.features(),old); QCOMPARE(c.meshVertices(),mesh); }
 void duplicateBusyRequest() { WorkspaceController c; seed(c); c.addBox(16,1,1); c.addBox(-1,1,1); QVERIFY(c.busy()); QTRY_COMPARE(c.operationState(),QString("Ready")); QCOMPARE(c.features().size(),2); }
 void cancelAndRestart() { WorkspaceController c; seed(c); c.addBox(14,1,1); c.cancel(); QCOMPARE(c.operationState(),QString("Cancelled")); QCOMPARE(c.features().size(),1); c.addBox(2,2,2); QTRY_COMPARE(c.operationState(),QString("Ready")); QCOMPARE(c.features().size(),2); }
 void timeout() { WorkspaceController c; seed(c); qputenv("PRECISION_WORKER_TIMEOUT_MS","100"); c.addBox(14,1,1); QTRY_COMPARE_WITH_TIMEOUT(c.operationState(),QString("Failed"),2000); QVERIFY(!c.busy()); QCOMPARE(c.features().size(),1); }
 void saveAsAndMultipleEdits() { QTemporaryDir dir; WorkspaceController c; seed(c); c.save(dir.filePath("a.pcad")); QVERIFY(!c.dirty()); c.addBox(2,2,2); QTRY_COMPARE(c.operationState(),QString("Ready")); c.addBox(3,3,3); QTRY_COMPARE(c.operationState(),QString("Ready")); c.save(dir.filePath("a.pcad")); QVERIFY(!c.dirty()); c.save(dir.filePath("b.pcad")); QVERIFY(QFile::exists(dir.filePath("b.pcad"))); QCOMPARE(c.documentPath(),dir.filePath("b.pcad")); }
 void failedOpenPreservesAll() { QTemporaryDir dir; WorkspaceController c; seed(c); c.save(dir.filePath("good.pcad")); c.addBox(2,2,2); QTRY_COMPARE(c.operationState(),QString("Ready")); auto old=c.features(),mesh=c.meshVertices(); DocumentRecord bad{1,"other",1,"mm",{{"bad","box","Bad",{},{{"dx",11},{"dy",1},{"dz",1}},false}}}; QVERIFY(DocumentStorage::save(dir.filePath("bad.pcad"),bad,std::nullopt).ok); c.open(dir.filePath("bad.pcad")); QTRY_COMPARE(c.operationState(),QString("Failed")); QCOMPARE(c.features(),old); QCOMPARE(c.meshVertices(),mesh); QCOMPARE(c.documentPath(),dir.filePath("good.pcad")); QVERIFY(c.dirty()); c.open(dir.filePath("good.pcad")); QTRY_COMPARE(c.operationState(),QString("Ready")); QVERIFY(!c.dirty()); QCOMPARE(c.features().size(),1); }
 void coordinateDomain_data() { QTest::addColumn<double>("dx"); QTest::addColumn<bool>("accepted"); QTest::newRow("vertex-boundary")<<26.0<<true; QTest::newRow("vertex-outside")<<27.0<<false; QTest::newRow("bounds-boundary")<<28.0<<true; QTest::newRow("bounds-outside")<<29.0<<false; }
 void coordinateDomain() { QFETCH(double,dx); QFETCH(bool,accepted); QTemporaryDir dir; WorkspaceController c; seed(c); c.save(dir.filePath("base.pcad")); QVERIFY(!c.dirty()); const auto old=c.features(), mesh=c.meshVertices(); c.addBox(dx,1,1); QTRY_COMPARE(c.operationState(),accepted?QString("Ready"):QString("Failed")); QCOMPARE(c.documentPath(),dir.filePath("base.pcad")); if(accepted) { QCOMPARE(c.features().size(),2); QVERIFY(c.dirty()); } else { QCOMPARE(c.features(),old); QCOMPARE(c.meshVertices(),mesh); QVERIFY(!c.dirty()); } }
 void aggregateCacheIsBounded() { qputenv("PRECISION_WORKER_CACHE_BYTES","6000"); QTemporaryDir dir; WorkspaceController c; seed(c); c.addBox(30,1,1); QTRY_COMPARE(c.operationState(),QString("Ready")); QCOMPARE(c.features().size(),2); c.save(dir.filePath("base.pcad")); const auto old=c.features(), mesh=c.meshVertices(); c.addBox(30,1,1); QTRY_COMPARE(c.operationState(),QString("Failed")); QVERIFY(c.errorMessage().contains("cache")); QCOMPARE(c.features(),old); QCOMPARE(c.meshVertices(),mesh); QCOMPARE(c.documentPath(),dir.filePath("base.pcad")); QVERIFY(!c.dirty()); QVERIFY(!c.busy()); }
 void imperialOpenIsRejected() { QTemporaryDir dir; WorkspaceController c; seed(c); const auto previous=c.features(); DocumentRecord record{1,"imperial",1,"in",{}}; QVERIFY(DocumentStorage::save(dir.filePath("in.pcad"),record,std::nullopt).ok); c.open(dir.filePath("in.pcad")); QCOMPARE(c.operationState(),QString("Failed")); QCOMPARE(c.features(),previous); QVERIFY(c.dirty()); QVERIFY(c.documentPath().isEmpty()); }
 void selectBodyAndEmptyMesh() { WorkspaceController c; seed(c); const auto id=c.features()[0].toMap()["id"].toString(); c.selectBody(id); QCOMPARE(c.selectedBody(),id); c.suppressFeature(id,true); QTRY_COMPARE(c.operationState(),QString("Ready")); QVERIFY(c.meshVertices().isEmpty()); }
 void editableDimensionsPreserveFeatureValues() { WorkspaceController c; c.addBox(40,30,20); QTRY_COMPARE(c.operationState(),QString("Ready")); const auto id=c.features()[0].toMap()["id"].toString(); const auto box=c.editableDimensions(id); QVERIFY(box.value("editable").toBool()); QCOMPARE(box.value("type").toString(),QString("box")); QCOMPARE(box.value("first").toDouble(),40.0); QCOMPARE(box.value("second").toDouble(),30.0); QCOMPARE(box.value("third").toDouble(),20.0); c.updateDimensions(id,50,30,20); QTRY_COMPARE(c.operationState(),QString("Ready")); const auto updated=c.editableDimensions(id); QCOMPARE(updated.value("first").toDouble(),50.0); QCOMPARE(updated.value("second").toDouble(),30.0); QCOMPARE(updated.value("third").toDouble(),20.0); c.updateDimensions(id,0,30,20); QTRY_COMPARE(c.operationState(),QString("Failed")); QCOMPARE(c.editableDimensions(id).value("first").toDouble(),50.0); }
 void editableDimensionsRejectUnsupportedAndWrongSelection() { QTemporaryDir dir; WorkspaceController c; const DocumentRecord record{1,"11111111-1111-4111-8111-111111111111",0,"mm",{{"left","box","Left",{},{{"dx",4},{"dy",5},{"dz",6}},false},{"right","box","Right",{},{{"dx",7},{"dy",8},{"dz",9}},false},{"combined","union","Union",{"left","right"},{},true}}}; QVERIFY(DocumentStorage::save(dir.filePath("unsupported.pcad"),record,std::nullopt).ok); c.open(dir.filePath("unsupported.pcad")); QTRY_COMPARE(c.operationState(),QString("Ready")); QVERIFY(!c.editableDimensions("missing").value("editable").toBool()); QVERIFY(!c.editableDimensions("combined").value("editable").toBool()); c.updateDimensions("combined",1,1,1); QTRY_COMPARE(c.operationState(),QString("Failed")); }
 void unaryEvaluationReceivesDependencyResult() { QTemporaryDir dir; WorkspaceController c; const DocumentRecord record{1,"22222222-2222-4222-8222-222222222222",0,"mm",{{"base","box","Base",{},{{"dx",4},{"dy",5},{"dz",6}},false},{"mesh","tessellate","Mesh",{"base"},{},false}}}; QVERIFY(DocumentStorage::save(dir.filePath("unary.pcad"),record,std::nullopt).ok); c.open(dir.filePath("unary.pcad")); QTRY_COMPARE(c.operationState(),QString("Ready")); QCOMPARE(c.features().size(),2); QVERIFY(!c.meshVertices().isEmpty()); }
 void evaluatorFailureRollsBackCandidate() { QTemporaryDir dir; WorkspaceController c; seed(c); const auto old=c.features(), mesh=c.meshVertices(); const DocumentRecord record{1,"33333333-3333-4333-8333-333333333333",0,"mm",{{"bad","box","Bad",{},{{"dx",4},{"dy",5},{"dz",6},{"extra",7}},false}}}; QVERIFY(DocumentStorage::save(dir.filePath("bad-schema.pcad"),record,std::nullopt).ok); c.open(dir.filePath("bad-schema.pcad")); QTRY_COMPARE(c.operationState(),QString("Failed")); QCOMPARE(c.features(),old); QCOMPARE(c.meshVertices(),mesh); QVERIFY(!c.busy()); }
};
QTEST_GUILESS_MAIN(WorkspaceControllerTest)
#include "tst_workspace_controller.moc"
